import Head from 'next/head'
import Header from '../Components/Header'
import Nav from '../Components/Nav'
import Result from '../Components/Result'
import request from '../utils/request'


export default function Home({results}) {
console.log(results)
  return (
    <div >
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {/*   */}

        {/* Header  */}
        <Header/>
        <Nav/>
        <Result results ={results}/>
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const requests = await fetch (`https://api.themoviedb.org/3${
    request[genre]?.url || request.fetchComedyMovies.url
  }`
  )  .then(res=>res.json ());
  return {
props:{
  results:requests.results
}
    }
}